CREATE TABLE [FS].[BalanceSheet] (
    [ID]                                             INT             IDENTITY (1, 1) NOT NULL,
    [Annual]                                         BIT             NOT NULL,
    [PeriodEnd]                                      DATE            NOT NULL,
    [Cash_and_Equivalents]                           DECIMAL (20, 4) NULL,
    [Short_Term_Investments]                         DECIMAL (20, 4) NULL,
    [Cash_and_Short_Term_Investments]                DECIMAL (20, 4) NULL,
    [Accounts_Receivable__Trade__Net]                DECIMAL (20, 4) NULL,
    [Receivables__Other]                             DECIMAL (20, 4) NULL,
    [Total_Receivables__Net]                         DECIMAL (20, 4) NULL,
    [Total_Inventory]                                DECIMAL (20, 4) NULL,
    [Prepaid_Expenses]                               DECIMAL (20, 4) NULL,
    [Other_Current_Assets__Total]                    DECIMAL (20, 4) NULL,
    [Total_Current_Assets]                           DECIMAL (20, 4) NULL,
    [Property_and_Plant_and_Equipment__Total__Gross] DECIMAL (20, 4) NULL,
    [Accumulated_Depreciation__Total]                DECIMAL (20, 4) NULL,
    [Goodwill__Net]                                  DECIMAL (20, 4) NULL,
    [Intangibles__Net]                               DECIMAL (20, 4) NULL,
    [Long_Term_Investments]                          DECIMAL (20, 4) NULL,
    [Other_Long_Term_Assets__Total]                  DECIMAL (20, 4) NULL,
    [Total_Assets]                                   DECIMAL (20, 4) NULL,
    [Accounts_Payable]                               DECIMAL (20, 4) NULL,
    [Accrued_Expenses]                               DECIMAL (20, 4) NULL,
    [Notes_Payable_and_Short_Term_Debt]              DECIMAL (20, 4) NULL,
    [Current_Port_of_LT_Debt_and_Capital_Leases]     DECIMAL (20, 4) NULL,
    [Other_Current_liabilities__Total]               DECIMAL (20, 4) NULL,
    [Total_Current_Liabilities]                      DECIMAL (20, 4) NULL,
    [Long_Term_Debt]                                 DECIMAL (20, 4) NULL,
    [Capital_Lease_Obligations]                      DECIMAL (20, 4) NULL,
    [Total_Long_Term_Debt]                           DECIMAL (20, 4) NULL,
    [Total_Debt]                                     DECIMAL (20, 4) NULL,
    [Deferred_Income_Tax]                            DECIMAL (20, 4) NULL,
    [Minority_Interest]                              DECIMAL (20, 4) NULL,
    [Other_Liabilities__Total]                       DECIMAL (20, 4) NULL,
    [Total_Liabilities]                              DECIMAL (20, 4) NULL,
    [Redeemable_Preferred_Stock__Total]              DECIMAL (20, 4) NULL,
    [Preferred_Stock__Non_Redeemable__Net]           DECIMAL (20, 4) NULL,
    [Common_Stock__Total]                            DECIMAL (20, 4) NULL,
    [Additional_PaidIn_Capital]                      DECIMAL (20, 4) NULL,
    [Retained_Earnings__Accumulated_Deficit_]        DECIMAL (20, 4) NULL,
    [Treasury_Stock__Common]                         DECIMAL (20, 4) NULL,
    [Other_Equity__Total]                            DECIMAL (20, 4) NULL,
    [Total_Equity]                                   DECIMAL (20, 4) NULL,
    [Total_Liabilities_and_Shareholders_Equity]      DECIMAL (20, 4) NULL,
    [Shares_Outs__Common_Stock_Primary_Issue]        DECIMAL (20, 4) NULL,
    [Total_Common_Shares_Outstanding]                DECIMAL (20, 4) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

