CREATE TABLE [FS].[IncomeStatement] (
    [ID]                                                    INT             IDENTITY (1, 1) NOT NULL,
    [Annual]                                                BIT             NOT NULL,
    [PeriodEnd]                                             DATE            NOT NULL,
    [Cash_and_Equivalents]                                  DECIMAL (20, 4) NULL,
    [Revenue]                                               DECIMAL (20, 4) NULL,
    [Other_Revenue_Total]                                   DECIMAL (20, 4) NULL,
    [Total_Revenue]                                         DECIMAL (20, 4) NULL,
    [Cost_of_Revenue_Total]                                 DECIMAL (20, 4) NULL,
    [Gross_Profit]                                          DECIMAL (20, 4) NULL,
    [Selling_and_General_and_Admin_Expenses_Total]          DECIMAL (20, 4) NULL,
    [Research_and_Development]                              DECIMAL (20, 4) NULL,
    [Depreciation_and_Amortization]                         DECIMAL (20, 4) NULL,
    [Interest_Expense__Income___less_Net_Operating]         DECIMAL (20, 4) NULL,
    [Unusual_Expense___Income__]                            DECIMAL (20, 4) NULL,
    [Other_Operating_Expenses_Total]                        DECIMAL (20, 4) NULL,
    [Total_Operating_Expense]                               DECIMAL (20, 4) NULL,
    [Operating_Income]                                      DECIMAL (20, 4) NULL,
    [Interest_Income__Expense___Net_NonOperating]           DECIMAL (20, 4) NULL,
    [Gain___Loss___on_Sale_of_Assets]                       DECIMAL (20, 4) NULL,
    [Other_Net]                                             DECIMAL (20, 4) NULL,
    [Income_Before_Tax]                                     DECIMAL (20, 4) NULL,
    [Income_After_Tax]                                      DECIMAL (20, 4) NULL,
    [Minority_Interest]                                     DECIMAL (20, 4) NULL,
    [Equity_In_Affiliates]                                  DECIMAL (20, 4) NULL,
    [Net_Income_Before_Extra_Items]                         DECIMAL (20, 4) NULL,
    [Accounting_Change]                                     DECIMAL (20, 4) NULL,
    [Discontinued_Operations]                               DECIMAL (20, 4) NULL,
    [Extraordinary_Item]                                    DECIMAL (20, 4) NULL,
    [Net_Income]                                            DECIMAL (20, 4) NULL,
    [Preferred_Dividends]                                   DECIMAL (20, 4) NULL,
    [Income_Available_to_Common_Excl_Extra_Items]           DECIMAL (20, 4) NULL,
    [Income_Available_to_Common_Incl_Extra_Items]           DECIMAL (20, 4) NULL,
    [Basic_Weighted_Average_Shares]                         DECIMAL (20, 4) NULL,
    [Basic_EPS_Excluding_Extraordinary_Items]               DECIMAL (20, 4) NULL,
    [Basic_EPS_Including_Extraordinary_Items]               DECIMAL (20, 4) NULL,
    [Dilution_Adjustment]                                   DECIMAL (20, 4) NULL,
    [Diluted_Weighted_Average_Shares]                       DECIMAL (20, 4) NULL,
    [Diluted_EPS_Excluding_Extraordinary_Items]             DECIMAL (20, 4) NULL,
    [Diluted_EPS_Including_Extraordinary_Items]             DECIMAL (20, 4) NULL,
    [Dividends_per_Share__less__Common_Stock_Primary_Issue] DECIMAL (20, 4) NULL,
    [Gross_Dividends__less__Common_Stock]                   DECIMAL (20, 4) NULL,
    [Net_Income_after_Stock_Based_Comp_Expense]             DECIMAL (20, 4) NULL,
    [Basic_EPS_after_Stock_Based_Comp_Expense]              DECIMAL (20, 4) NULL,
    [Diluted_EPS_after_Stock_Based_Comp_Expense]            DECIMAL (20, 4) NULL,
    [Depreciation_Supplemental]                             DECIMAL (20, 4) NULL,
    [Total_Special_Items]                                   DECIMAL (20, 4) NULL,
    [Normalized_Income_Before_Taxes]                        DECIMAL (20, 4) NULL,
    [Effect_of_Special_Items_on_Income_Taxes]               DECIMAL (20, 4) NULL,
    [Income_Taxes_Ex_Impact_of_Special_Items]               DECIMAL (20, 4) NULL,
    [Normalized_Income_After_Taxes]                         DECIMAL (20, 4) NULL,
    [Normalized_Income_Avail_to_Common]                     DECIMAL (20, 4) NULL,
    [Basic_Normalized_EPS]                                  DECIMAL (20, 4) NULL,
    [Diluted_Normalized_EPS]                                DECIMAL (20, 4) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

