//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialSnapshot
    {
        public System.DateTime QueryDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<decimal> Beta { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> Dividend { get; set; }
        public Nullable<decimal> DividendYield { get; set; }
        public Nullable<decimal> EarningsPerShare { get; set; }
        public Nullable<decimal> FiftyTwoWeekLow { get; set; }
        public Nullable<decimal> FiftyTwoWeekHigh { get; set; }
        public Nullable<decimal> InstitutionalOwnership { get; set; }
        public Nullable<decimal> MarketCap { get; set; }
        public Nullable<decimal> PriceEarnings { get; set; }
        public Nullable<decimal> RangeLow { get; set; }
        public Nullable<decimal> RangeHigh { get; set; }
        public Nullable<decimal> Shares { get; set; }
        public Nullable<decimal> VolumeAverage { get; set; }
        public Nullable<decimal> VolumeDaily { get; set; }
    
        public virtual InfoCompany InfoCompany { get; set; }
    }
}
