//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeStatement
    {
        public IncomeStatement()
        {
            this.InfoCompanies = new HashSet<InfoCompany>();
        }
    
        public int ID { get; set; }
        public bool Annual { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public Nullable<decimal> Cash_and_Equivalents { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Other_Revenue_Total { get; set; }
        public Nullable<decimal> Total_Revenue { get; set; }
        public Nullable<decimal> Cost_of_Revenue_Total { get; set; }
        public Nullable<decimal> Gross_Profit { get; set; }
        public Nullable<decimal> Selling_and_General_and_Admin_Expenses_Total { get; set; }
        public Nullable<decimal> Research_and_Development { get; set; }
        public Nullable<decimal> Depreciation_and_Amortization { get; set; }
        public Nullable<decimal> Interest_Expense__Income___less_Net_Operating { get; set; }
        public Nullable<decimal> Unusual_Expense___Income__ { get; set; }
        public Nullable<decimal> Other_Operating_Expenses_Total { get; set; }
        public Nullable<decimal> Total_Operating_Expense { get; set; }
        public Nullable<decimal> Operating_Income { get; set; }
        public Nullable<decimal> Interest_Income__Expense___Net_NonOperating { get; set; }
        public Nullable<decimal> Gain___Loss___on_Sale_of_Assets { get; set; }
        public Nullable<decimal> Other_Net { get; set; }
        public Nullable<decimal> Income_Before_Tax { get; set; }
        public Nullable<decimal> Income_After_Tax { get; set; }
        public Nullable<decimal> Minority_Interest { get; set; }
        public Nullable<decimal> Equity_In_Affiliates { get; set; }
        public Nullable<decimal> Net_Income_Before_Extra_Items { get; set; }
        public Nullable<decimal> Accounting_Change { get; set; }
        public Nullable<decimal> Discontinued_Operations { get; set; }
        public Nullable<decimal> Extraordinary_Item { get; set; }
        public Nullable<decimal> Net_Income { get; set; }
        public Nullable<decimal> Preferred_Dividends { get; set; }
        public Nullable<decimal> Income_Available_to_Common_Excl_Extra_Items { get; set; }
        public Nullable<decimal> Income_Available_to_Common_Incl_Extra_Items { get; set; }
        public Nullable<decimal> Basic_Weighted_Average_Shares { get; set; }
        public Nullable<decimal> Basic_EPS_Excluding_Extraordinary_Items { get; set; }
        public Nullable<decimal> Basic_EPS_Including_Extraordinary_Items { get; set; }
        public Nullable<decimal> Dilution_Adjustment { get; set; }
        public Nullable<decimal> Diluted_Weighted_Average_Shares { get; set; }
        public Nullable<decimal> Diluted_EPS_Excluding_Extraordinary_Items { get; set; }
        public Nullable<decimal> Diluted_EPS_Including_Extraordinary_Items { get; set; }
        public Nullable<decimal> Dividends_per_Share__less__Common_Stock_Primary_Issue { get; set; }
        public Nullable<decimal> Gross_Dividends__less__Common_Stock { get; set; }
        public Nullable<decimal> Net_Income_after_Stock_Based_Comp_Expense { get; set; }
        public Nullable<decimal> Basic_EPS_after_Stock_Based_Comp_Expense { get; set; }
        public Nullable<decimal> Diluted_EPS_after_Stock_Based_Comp_Expense { get; set; }
        public Nullable<decimal> Depreciation_Supplemental { get; set; }
        public Nullable<decimal> Total_Special_Items { get; set; }
        public Nullable<decimal> Normalized_Income_Before_Taxes { get; set; }
        public Nullable<decimal> Effect_of_Special_Items_on_Income_Taxes { get; set; }
        public Nullable<decimal> Income_Taxes_Ex_Impact_of_Special_Items { get; set; }
        public Nullable<decimal> Normalized_Income_After_Taxes { get; set; }
        public Nullable<decimal> Normalized_Income_Avail_to_Common { get; set; }
        public Nullable<decimal> Basic_Normalized_EPS { get; set; }
        public Nullable<decimal> Diluted_Normalized_EPS { get; set; }
    
        public virtual ICollection<InfoCompany> InfoCompanies { get; set; }
    }
}
