//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoExchange
    {
        public InfoExchange()
        {
            this.InfoCompanies = new HashSet<InfoCompany>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InfoCompany> InfoCompanies { get; set; }
    }
}
