//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCompany
    {
        public InfoCompany()
        {
            this.FinancialSnapshots = new HashSet<FinancialSnapshot>();
            this.KeyAccountingStats = new HashSet<KeyAccountingStat>();
            this.InfoExchanges = new HashSet<InfoExchange>();
            this.BalanceSheets = new HashSet<BalanceSheet>();
            this.StatementOfCashFlows = new HashSet<StatementOfCashFlow>();
            this.IncomeStatements = new HashSet<IncomeStatement>();
            this.InfoIndustries = new HashSet<InfoIndustry>();
            this.InfoLists = new HashSet<InfoList>();
            this.InfoSectors = new HashSet<InfoSector>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Ticker { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<FinancialSnapshot> FinancialSnapshots { get; set; }
        public virtual ICollection<KeyAccountingStat> KeyAccountingStats { get; set; }
        public virtual ICollection<InfoExchange> InfoExchanges { get; set; }
        public virtual ICollection<BalanceSheet> BalanceSheets { get; set; }
        public virtual ICollection<StatementOfCashFlow> StatementOfCashFlows { get; set; }
        public virtual ICollection<IncomeStatement> IncomeStatements { get; set; }
        public virtual ICollection<InfoIndustry> InfoIndustries { get; set; }
        public virtual ICollection<InfoList> InfoLists { get; set; }
        public virtual ICollection<InfoSector> InfoSectors { get; set; }
    }
}
