//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyAccountingStat
    {
        public int CompanyID { get; set; }
        public System.DateTime Period { get; set; }
        public bool Annual { get; set; }
        public Nullable<decimal> NetProfitMargin { get; set; }
        public Nullable<decimal> OperatingMargin { get; set; }
        public Nullable<decimal> EBITDMargin { get; set; }
        public Nullable<decimal> ReturnOnAverageAssets { get; set; }
        public Nullable<decimal> ReturnOnAverageEquity { get; set; }
        public Nullable<int> Employees { get; set; }
        public Nullable<int> CDPScoreN { get; set; }
        public string CDPScoreL { get; set; }
    
        public virtual InfoCompany InfoCompany { get; set; }
    }
}
