//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockPortfolioEntities7 : DbContext
    {
        public StockPortfolioEntities7()
            : base("name=StockPortfolioEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<FinancialSnapshot> FinancialSnapshots { get; set; }
        public virtual DbSet<InfoCompany> InfoCompanies { get; set; }
        public virtual DbSet<KeyAccountingStat> KeyAccountingStats { get; set; }
        public virtual DbSet<InfoExchange> InfoExchanges { get; set; }
        public virtual DbSet<BalanceSheet> BalanceSheets { get; set; }
        public virtual DbSet<IncomeStatement> IncomeStatements { get; set; }
        public virtual DbSet<StatementOfCashFlow> StatementOfCashFlows { get; set; }
        public virtual DbSet<InfoIndustry> InfoIndustries { get; set; }
        public virtual DbSet<InfoList> InfoLists { get; set; }
        public virtual DbSet<InfoSector> InfoSectors { get; set; }
    }
}
