//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupTickers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementOfCashFlow
    {
        public StatementOfCashFlow()
        {
            this.InfoCompanies = new HashSet<InfoCompany>();
        }
    
        public int ID { get; set; }
        public bool Annual { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public Nullable<decimal> Net_Income_and_Starting_Line { get; set; }
        public Nullable<decimal> Depreciation_and_Depletion { get; set; }
        public Nullable<decimal> Amortization { get; set; }
        public Nullable<decimal> Deferred_Taxes { get; set; }
        public Nullable<decimal> NonCash_Items { get; set; }
        public Nullable<decimal> Changes_in_Working_Capital { get; set; }
        public Nullable<decimal> Cash_from_Operating_Activities { get; set; }
        public Nullable<decimal> Capital_Expenditures { get; set; }
        public Nullable<decimal> Other_Investing_Cash_Flow_Items__Total { get; set; }
        public Nullable<decimal> Cash_from_Investing_Activities { get; set; }
        public Nullable<decimal> Financing_Cash_Flow_Items { get; set; }
        public Nullable<decimal> Total_Cash_Dividends_Paid { get; set; }
        public Nullable<decimal> Issuance__Retirement__of_Stock__Net { get; set; }
        public Nullable<decimal> Issuance__Retirement__of_Debt__Net { get; set; }
        public Nullable<decimal> Cash_from_Financing_Activities { get; set; }
        public Nullable<decimal> Foreign_Exchange_Effects { get; set; }
        public Nullable<decimal> Net_Change_in_Cash { get; set; }
        public Nullable<decimal> Cash_Interest_Paid__Supplemental { get; set; }
        public Nullable<decimal> Cash_Taxes_Paid__Supplemental { get; set; }
    
        public virtual ICollection<InfoCompany> InfoCompanies { get; set; }
    }
}
